-- write("Number: ")
-- num = read()
-- shell.run("label", "set", "mining"..num)
shell.run("rm", "get")
shell.run("cp", "disk/get", ".")
-- shell.run("get", "proj", "Mining")
-- shell.run("update", "mining")
